// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GreeterController from "./greeter_controller"
application.register("greeter", GreeterController)

import MapsController from "./maps_controller"
application.register("maps", MapsController)

import TestController from "./test_controller"
application.register("test", TestController)
