// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BaseMapController from "./base_map_controller"
application.register("base-map", BaseMapController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapsController from "./maps_controller"
application.register("maps", MapsController)

import MarkerController from "./marker_controller"
application.register("marker", MarkerController)

import TestController from "./test_controller"
application.register("test", TestController)
