services:
  db:
    image: postgres:15.12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: myfavramen
      POSTGRES_DB: myfavramen_development
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myfavramen"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - bundle_cache:/usr/local/bundle
      - /app/node_modules   # node_modulesを除外
      - /app/app/assets/builds  # buildsディレクトリを除外（重要）
      - /app/tmp            # tmpディレクトリも除外すると良い
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://myfavramen:password@db:5432/myfavramen_development
      RAILS_ENV: development
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
    tty: true
    stdin_open: true
    restart: always

volumes:
  postgres_data:
  node_modules:
  bundle_cache: